# Generated by Django 4.2.6 on 2023-10-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profileimg',
            new_name='profilepic',
        ),
    ]
