# Generated by Django 4.2.6 on 2023-10-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionyearmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionstart', models.CharField(max_length=50)),
                ('sessionend', models.CharField(max_length=50)),
            ],
        ),
    ]
